config/routes.rb
  Rails.application.routes.draw do
  get 'orders/new'
  resources :order_items
  get 'cart', to: 'cart#show'
  root 'home#index'
  resources :books
  resources :home 
  devise_for :users

  #root to: 'books#index'
  get '/index' => 'books#index'
  get :send_book_mail, to: 'books#send_book_mail', as: :send_book_mail
  #root to: 'books#list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, :isbn, :image, :category,
            :language, presence: true
  belongs_to :user
  has_many :poly_images, as: :imageable

  has_one_attached :image
  has_one_attached :preview_pdf
  has_one_attached :pdf_file 
  
  has_many :order_items, as: :orderable
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect{|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :orderable, polymorphic: true
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    #If there is a record 
    if presisted?
      self[:unit_price]
    else
      book.price
    end
  end

  def total
    return unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end
  def set_total
    self[:total] = total * quantity
  end
end

app/models/poly_image.rb
class PolyImage < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :books

  has_many :poly_images, as: :imageable
  has_one_attached :image
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  include ApplicationHelper

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  
  def index
    #binding.pry
    @books = Book.all
    if params[:search].blank?
    else
      @books = Book.where('title LIKE ? or category LIKE ?','%' + params[:search] + '%',
                                                            '%' + params[:search] + '%')
      #binding.pry
    end
    
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def send_book_mail
    @book = Book.find(params[:id])
    BookMailer.book_send(@book).deliver_now
    flash[:notice] = "book has been sent."
    redirect_to root_path(@book.id)
  end

  private
    
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :date, :isbn, :total_pages,
                                   :user_id, :image, :price, :description,
                                   :preview_pdf, :pdf_file, :category,
                                   :language)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_book, only: %i[show]
  def index
    @books = Book.all
    if params[:search].blank?
    else
      @books = Book.where('title LIKE ? or category LIKE ?','%' + params[:search] + '%',
                                                            '%' + params[:search] + '%')
      end
  end


  def show
    # @book = Book.find(params[:book_id])
  end
  
  # def new
  # end

  private
   # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order

  def create
    @order_item = @order.order_items.new(order_params)
    @order.save
    session[:order_id] = @order_id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private

  def order_params
    params.require(:order_item).permit(:book_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
    @book = Book.find(params[:book_id])
  end

  def create
    @order = Order.new(order_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :success then "alert alert-success"
      when :notice then "alert alert-success"
      when :alert then "alert alert-danger"
      when :error then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="alert alert alert-danger">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul class="alert alert alert-danger">
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title , class: 'form-control form-control-lg'%>
  </div>
  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category , class: 'form-control form-control-lg'%>
  </div>
  <div class="form-group">
    <%= form.label :language %>
    <%= form.text_field :language , class: 'form-control form-control-lg'%>
  </div>
  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_select :date, class: 'form-control form-control-lg' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control form-control-lg'%>
  </div>

  <div class="form-group">
    <%= form.label :isbn %>
    <%= form.number_field :isbn, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group">
    <%= form.label :total_pages %>
    <%= form.number_field :total_pages, 
                          class: 'form-control form-control-lg' %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control form-control-lg' %> 
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control form-control-lg' %> 
  </div>
  <div class="form-group">
    <%= form.label :preview_pdf %>
    <%= form.file_field :preview_pdf,direct_upload: true, 
                         accept: 'application/pdf' ,
                         class: 'form-control form-control-lg' %> 
  </div>
  <div class="form-group">
    <%= form.label :pdf_file %>
    <%= form.file_field :pdf_file ,direct_upload: true, 
                         accept: 'application/pdf',
                         class: 'form-control form-control-lg' %> 
  </div>  
  <div class="form-group">
    <%#= form.label :total_pages %>
    <%= form.number_field :user_id, id: :book_user_id, class: 'form-control form', value: current_user.id, type: :hidden %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-header">
        <h1 class="card-title text-center">Editing Book</h1>
      </div>
      <div class="card-body">
        <%= render 'form', book: @book %>

        <%= link_to 'Show', @book, class: 'btn btn-primary btn-lg btn-block' %> <br>
        <%= link_to 'Back', books_path, class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
  </div>
</div>      

app/views/books/index.html.erb
<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-header">
        <h2 class="card-title text-center">Find Your Book</h2>
      </div>  
      <div class="card-body">
        <%= form_with url: "/index", method: :get do %>
          <%= text_field_tag(:search, params[:search]) %>
          <%= submit_tag("Search", name: nil)%>
        <%end%>
      </div>
    </div>  
  </div>    
</div>
<br><br>  

<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-header">
        <h1 class="card-title text-center">Books</h1>
      </div>  
    </div>
  </div>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Category</th>
      <th scope="col">Language</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col">Isbn</th>
      <th scope="col">Total pages</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Destroy</th>

    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.category%></td>
        <td><%= book.language%></td>
        <td><%= book.author %></td>
        <td><%= book.date %></td>
        <td><%= book.isbn %></td>
        <td><%= book.total_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%#= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-header">
        <h1 class="card-title text-center">New Book</h1>
      </div>
      <div class="card-body">
        <%= render 'form', book: @book %>

        <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</div>      

app/views/books/show.html.erb
<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-body">
        <div class="form-group">
          <p class="card-title text-center">
            <%= image_tag(@book.image, style:'width:100%') %>
          </p>
        </div>  
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Title:</strong>
            <%= @book.title %>
          </p>
        </div>

        <div class="form-group">
          <p class="card-title text-center">
            <strong>Category:</strong>
            <%= @book.category %>
          </p>
        </div>
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Language:</strong>
            <%= @book.language %>
          </p>
        </div>
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Author:</strong>
            <%= @book.author %>
          </p>
        </div>
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Date:</strong>
            <%= @book.date %>
          </p>
        </div>
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Description:</strong>
            <%= @book.description %>
          </p>
        </div>
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Isbn:</strong>
            <%= @book.isbn %>
          </p>
        </div>
        <div class="form-group">
          <p class="card-title text-center">
            <strong>Total pages:</strong>
            <%= @book.total_pages %>
          </p>
        </div> 
        <div class="form-group">
          <p class="card-title text-center">
            <%= link_to 'Preview_PDF', @book.preview_pdf, class:'btn btn-primary' %>
          </p>
        </div>    

        <div class="form-group">
          <p class="card-title text-center">
            <%= link_to 'PDF', @book.pdf_file, class:'btn btn-primary' %>
          </p>
        </div>
        <div class="form-group">
          <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary btn-lg btn-block' %> <br>
          <%= link_to 'Back', books_path, class: 'btn btn-primary btn-lg btn-block' %>
        </div>

      <div class="card-body"> 
    </div>
  </div>
</div>        

app/views/cart/_caet.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{currnt_order.subtotal}", cart_path%>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
  <h3><%= item.book.title%></h3>
  <h3><%= item.price%></h3>
<%= form_with model: item do |f|%>
  <%= f.hidden_field :book_id, value: item.book.id %>
  <%= f.number_field :quantity, value: item.quantity.to_i %>
  <%= f.submit "Update Card" %>
  <%= link_to "Remove Items", item, method: :delete, remote: true %>
<% end %>
  <h2>Subtotal: <%= item.total %></h2>    
<% end %>

<h3> Your current order has a total of <%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart_item">
  <%= render 'cart_items'%>
</div>
<hr>

app/views/home/index.html.erb
<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-header">
        <h2 class="card-title text-center">Book List</h2>
      </div>  
    </div>  
  </div>    
</div>
<br><br> 
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-3 mt-5">
        <div class="card h-100">
          <%=  image_tag(book.image, style: 'height: 15vw;') %>
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <p class="card-text"></p>
            <%= link_to 'show', home_path(book) %>
          </div>
        </div>
      </div>
    <%end%>  
  </div>
</div>

app/views/home/show.html.erb
<div class='container'>
  <div class='col-md-7 mx-md-auto mt-5'>
    <div class='card shadow'>
      <div class='card-body'>  
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Image:</strong>
            <%= image_tag(@book.image, style:'width:100%') %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Title:</strong>
            <%= @book.title %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Category:</strong>
            <%= @book.category %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Language:</strong>
            <%= @book.language %>
          </p>
        </div>

        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Author:</strong>
            <%= @book.author %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Date:</strong>
            <%= @book.date %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Description:</strong>
            <%= @book.description %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Isbn:</strong>
            <%= @book.isbn %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <strong>Total pages:</strong>
            <%= @book.total_pages %>
          </p>
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <%= link_to 'Preview_PDF', @book.preview_pdf %>|------|
            
            <%= link_to 'PDF_File', :controller => 'books', :action => 'send_book_mail', :id => @book.id %>
            <%= link_to 'PDF', orders_new_path(book_id: @book.id), class:'btn btn-primary'%>
          </p>
          
        </div>
        <div class='form-group'>
          <p class='card-title text-center'>
            <%= link_to 'Home', root_path, class:'btn btn-primary btn-lg btn-block' %>
          </p>
        </div>
       
      <div class='card-body'> 
    </div>
  </div>
</div>        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart'%>");

app/views/order_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items'%>");

app/views/order_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items'%>");

app/views/orders/new.html.erb
<div class="container">
  <div class="col-md-7 mx-md-auto mt-5">
    <div class="card shadow">
      <div class="card-header">
        <h2 class="card-title text-center">Book Orders</h2>
      </div>
      <div class='form-group'>
        <p class='card-title text-center'>
          <!-- <strong>Image:</strong> -->
          <%= image_tag(@book.image, style:'width:100%, height:50%') %>
        </p>
      </div>
      <div class='form-group'>
        <p class='card-title text-center'>
          <strong>Title:</strong>
          <%= @book.title %>
        </p>
      </div>
      <div class='form-group'>
        <p class='card-title text-center'>
          <strong>Language:</strong>
          <%= @book.language %>
        </p>
      </div>
      <div class='form-group'>
        <p class='card-title text-center'>
          <strong>Price:</strong>
          <%= @book.price %>
        </p>
      </div>
      <div class='form-group'>
        <p class='card-title text-center'>
          <strong>Description:</strong>
          <%= @book.description %>
        </p>
      </div>
      <div class='form-group'>
        <p class='card-title text-center'>
          <%= link_to 'Order',  class:'btn btn-primary btn-lg btn-block' %>
        </p>
      </div>
    </div>
  </div>
</div>      

app/views/shared/_flash.html.erb
<div id="flash" class='text-center mt-4'>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %>">
      <% unless value == true  %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'Book-Finder', '/', class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--  -->
    </ul>
    <ul class='navbar-nav'>
      <li class='nav-item text-justify d-flex justify-content-center'>
        <%#= form_with url: "/home", method: :get do %>
          <%#= text_field_tag(:search, params[:search]) %>
          <%#= submit_tag("Search", name: nil)%>
        <%#end%>
          <li>
          <%= link_to 'Home', root_path, class: 'nav-link text-white' %>
          </li>
        <% if user_signed_in? %>
          <li>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Action
              </button>
              <div class="dropdown-menu">
                <%= link_to 'list-Book', books_path, class:"dropdown-item" %>
                
                <%= link_to 'Add-New-Book', new_book_path, class:"dropdown-item" %>
              </div>
            </div>
          </li>
           <li>
          <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link text-white' %>
          </li>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link text-white' %>
        
        <li>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link text-white' %>
        </li>
        <% end %>
      </li>
    </ul>  
  </div>
</nav>